"""Shared constants package."""

from .lottery import (
    LOTTERY_MIN_NUMBER,
    LOTTERY_MAX_NUMBER,
    NUMBERS_PER_GAME,
    DEFAULT_SUGGESTIONS_COUNT,
    RECENT_DRAWS_WINDOW,
    HISTORICAL_DATA_FILENAME,
)

__all__ = [
    "LOTTERY_MIN_NUMBER",
    "LOTTERY_MAX_NUMBER",
    "NUMBERS_PER_GAME",
    "DEFAULT_SUGGESTIONS_COUNT",
    "RECENT_DRAWS_WINDOW",
    "HISTORICAL_DATA_FILENAME",
]
